// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCM.Web.Entities;

namespace TCM.Web.Migrations
{
    [DbContext(typeof(Clubs.ClubDataContext))]
    partial class ClubDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TCM.Web.Entities.Clubs+Club", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Exists");

                    b.Property<int?>("MembershipCount");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("TCM.Web.Entities.Clubs+MetricsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClubId");

                    b.Property<int?>("Goals");

                    b.Property<int?>("Members");

                    b.Property<string>("MonthEnd");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("MetricsHistory");
                });

            modelBuilder.Entity("TCM.Web.Entities.Clubs+MetricsHistory", b =>
                {
                    b.HasOne("TCM.Web.Entities.Clubs+Club")
                        .WithMany("MetricsHistory")
                        .HasForeignKey("ClubId");
                });
#pragma warning restore 612, 618
        }
    }
}
